### ISSUE TITLE
运行run.py文件报错

### ISSUE THREAD

**Issue by adb1145141** [devcxl/R4AG-OpenWRT#1]
root@yoko-To-Be-Filled-By-O-E-M:~# python3 '/4A/R4AG-OpenWRT/run.py' 
Traceback (most recent call last):
  File "/4A/R4AG-OpenWRT/run.py", line 8, in <module>
    with tarfile.open("build/2023-09-02--21 51 04.tar.gz", "w:gz") as tar:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tarfile.py", line 1822, in open
    return func(name, filemode, fileobj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tarfile.py", line 1870, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/gzip.py", line 192, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'build/2023-09-02--21 51 04.tar.gz'
这文件有啥用啊？

**Comment by devcxl** [comment]
这个是把文件打包 通过小米路由器的恢复备份功能上传到路由器里 实现破解的 你项目文录里加一个build文件夹就好了.

**Comment by adb1145141** [comment]
我已经修改了，但还是报错
root@yoko-To-Be-Filled-By-O-E-M:/4A/R4AG-OpenWRT# python3 run.py
200
{"code":1629,"msg":"解压失败，可能文件已经损坏"}
200
{"download":0,"bandwidth":0,"code":0}

**Comment by devcxl** [comment]
那你从小米路由器上新建个备份文件，把这个文件放在build文件夹。再把run.py里的所有`2023-09-02--21 51 04.tar.gz` 改成你的备份文件名试试。

**Comment by adb1145141** [comment]
已经按照你的说法去做了，运行了很多次，却还是报错
我已经怀疑我的系统是不是没法用，系统是Ubuntu24.04

**Comment by devcxl** [comment]
运行run.py这块跟什么系统不相关，我确认下，你根据教程降级固件版本了么？

**Comment by adb1145141** [comment]
已经按照了

**Comment by devcxl** [comment]
那你最后试试，自己手动将`speedtest_urls.xml`和`script.sh`打包。如果还不行的话那我也想不到会是什么问题了。

还有，我建议别折腾小米路由器4a千兆版了，根本没多少存储空间，费功夫，最后刷成功了很多比较大的软件没办法装，挺鸡肋的。
